### ISSUE TITLE
无法在“节点”上执行“insertBefore”：要在其之前插入新节点的节点不是此节点的子节点。

### ISSUE THREAD

**Issue by xiaolin20622** [ossrs/srs-cloud#57]
您遇到错误！
名称：NotFound错误消息
：无法在“节点”上执行“insertBefore”：要在其之前插入新节点的节点不是此节点的子节点。
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at kl (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1141971)
    at kl (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1142044)
    at wl (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1141469)
    at Tc (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1154228)
    at t.unstable_runWithPriority (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1245445)
    at Ki (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1097521)
    at Fc (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1152389)
    at xc (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1148475)
    at http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1097744
    at t.unstable_runWithPriority (http://8.218.33.142/mgmt/static/js/main.d54a682c.js:2:1245445)

在多平台转推后就会报这个错误，请问是什么原因

**Comment by winlinvip** [comment]
Can't replay.
